### ISSUE TITLE
Broken on PowerShell Core 7

### ISSUE THREAD

**Issue by pshirshov** [cspotcode/PS-GuiCompletion#15] opened 2020-09-21 14:56 UTC
I'm getting this when completion triggers:

```
❯ ls -la /SAn exception occurred in custom key handler, see $error for more information: Exception calling "GetBufferContents" with "1" argument(s): "The method or operation is not implemented."
```

**Comment by cspotcode** [comment] 2020-09-21 16:20
Duplicate of #13 ?

**Comment by pshirshov** [comment] 2020-09-21 16:54
Yeah, seems like.

**Comment by cspotcode** [comment] 2020-09-21 16:57
Alright, I'll close this then.  Unfortunately this is effectively Windows-only.

**Closed as completed by cspotcode** 2020-09-21 16:57 UTC
